dict = {   'Almonds Walnuts Cashews Broad Bean Peanut Processing': {   'name': 'Almonds '
                                                                        'Walnuts '
                                                                        'Cashews '
                                                                        'Broad '
                                                                        'Bean '
                                                                        'Peanut '
                                                                        'Processing',
                                                                'url': 'https://www.twothousand.com/almonds-walnuts-cashews-broad-bean-peanut-processing'}, 
    'Bain Maries': {   'name': 'Bain Maries',
                       'url': 'https://www.twothousand.com/bain-maries'},
    'Bakery Cases': {   'name': 'Bakery Cases',
                        'url': 'https://www.twothousand.com/bakery-cases'},
    'Bakery Pans': {   'name': 'Bakery Pans',
                       'url': 'https://www.twothousand.com/bakery-pans'},
    'Bakery Proofers': {   'name': 'Bakery Proofers',
                           'url': 'https://www.twothousand.com/bakery-proofers'},
    'Bakery Racks': {   'name': 'Bakery Racks',
                        'url': 'https://www.twothousand.com/bakery-racks'},
    'Bakery Water Chillers': {   'name': 'Bakery Water Chillers',
                                 'url': 'https://www.twothousand.com/bakery-water-chillers'},
    'Baking Ovens': {   'name': 'Baking Ovens',
                        'url': 'https://www.twothousand.com/baking-ovens'},
    'Bar Refrigerators': {   'name': 'Bar Refrigerators',
                             'url': 'https://www.twothousand.com/bar-refrigerators'},
    'Beverage Dispensers': {   'name': 'Beverage Dispensers',
                               'url': 'https://www.twothousand.com/beverage-dispensers'},
    'Beverage Refrigerators': {   'name': 'Beverage Refrigerators',
                                  'url': 'https://www.twothousand.com/beverage-refrigerators'},
    'Blast Chiller Freezers': {   'name': 'Blast Chiller Freezers',
                                  'url': 'https://www.twothousand.com/blast-chiller-freezers'},
    'Bowl Cutters': {   'name': 'Bowl Cutters',
                        'url': 'https://www.twothousand.com/bowl-cutters'},
    'Bread Slicers': {   'name': 'Bread Slicers',
                         'url': 'https://www.twothousand.com/bread-slicers'},
    'Buffet Juice Dispenser': {   'name': 'Buffet Juice Dispenser',
                                  'url': 'https://www.twothousand.com/buffet-juice-dispenser'},
    'Cake Cutting Machines': {   'name': 'Cake Cutting Machines',
                                 'url': 'https://www.twothousand.com/cake-cutting-machines'},
    'Candy Floss Machines': {   'name': 'Candy Floss Machines',
                                'url': 'https://www.twothousand.com/candy-floss-machines'},
    'Carton Sealers': {   'name': 'Carton Sealers',
                          'url': 'https://www.twothousand.com/carton-sealers'},
    'Carton Strapping Machines': {   'name': 'Carton Strapping Machines',
                                     'url': 'https://www.twothousand.com/carton-strapping-machines'},
    'Chafe Dish': {   'name': 'Chafe Dish',
                      'url': 'https://www.twothousand.com/chafe-dish'},
    'Chicken Rotisserie Ovens': {   'name': 'Chicken Rotisserie Ovens',
                                    'url': 'https://www.twothousand.com/chicken-rotisserie-ovens'},
    'Chinese Cooking Ranges': {   'name': 'Chinese Cooking Ranges',
                                  'url': 'https://www.twothousand.com/chinese-cooking-ranges'},
    'Churro Machines': {   'name': 'Churro Machines',
                           'url': 'https://www.twothousand.com/churro-machines'},
    'Coffee Hotplate': {   'name': 'Coffee Hotplate',
                           'url': 'https://www.twothousand.com/coffee-hotplate'},
    'Combi Ovens': {   'name': 'Combi Ovens',
                       'url': 'https://www.twothousand.com/combi-ovens'},
    'Commercial Blenders': {   'name': 'Commercial Blenders',
                               'url': 'https://www.twothousand.com/commercial-blenders'},
    'Commercial Chocolate Machines': {   'name': 'Commercial Chocolate '
                                                 'Machines',
                                         'url': 'https://www.twothousand.com/commercial-chocolate-machines'},
    'Commercial Coffee Makers': {   'name': 'Commercial Coffee Makers',
                                    'url': 'https://www.twothousand.com/commercial-coffee-makers'},
    'Commercial Convection Ovens': {   'name': 'Commercial Convection Ovens',
                                       'url': 'https://www.twothousand.com/commercial-convection-ovens'},
    'Commercial Electric Hot Plates': {   'name': 'Commercial Electric Hot '
                                                  'Plates',
                                          'url': 'https://www.twothousand.com/commercial-electric-hot-plates'},
    'Commercial Faucets': {   'name': 'Commercial Faucets',
                              'url': 'https://www.twothousand.com/commercial-faucets'},
    'Commercial Fryers': {   'name': 'Commercial Fryers',
                             'url': 'https://www.twothousand.com/commercial-fryers'},
    'Commercial Griddles': {   'name': 'Commercial Griddles',
                               'url': 'https://www.twothousand.com/commercial-griddles'},
    'Commercial Grills': {   'name': 'Commercial Grills',
                             'url': 'https://www.twothousand.com/commercial-grills'},
    'Commercial Hoods': {   'name': 'Commercial Hoods',
                            'url': 'https://www.twothousand.com/commercial-hoods'},
    'Commercial Ice Makers': {   'name': 'Commercial Ice Makers',
                                 'url': 'https://www.twothousand.com/commercial-ice-makers'},
    'Commercial Induction Cooktop': {   'name': 'Commercial Induction Cooktop',
                                        'url': 'https://www.twothousand.com/commercial-induction-cooktop'},
    'Commercial Meat Grinders': {   'name': 'Commercial Meat Grinders',
                                    'url': 'https://www.twothousand.com/commercial-meat-grinders'},
    'Commercial Meat Slicers': {   'name': 'Commercial Meat Slicers',
                                   'url': 'https://www.twothousand.com/commercial-meat-slicers'},
    'Commercial Mixers': {   'name': 'Commercial Mixers',
                             'url': 'https://www.twothousand.com/commercial-mixers'},
    'Commercial Orange Juicers': {   'name': 'Commercial Orange Juicers',
                                     'url': 'https://www.twothousand.com/commercial-orange-juicers'},
    'Commercial Pizza Ovens': {   'name': 'Commercial Pizza Ovens',
                                  'url': 'https://www.twothousand.com/commercial-pizza-ovens'},
    'Commercial Potato Peelers': {   'name': 'Commercial Potato Peelers',
                                     'url': 'https://www.twothousand.com/commercial-potato-peelers'},
    'Commercial Prep Tables': {   'name': 'Commercial Prep Tables',
                                  'url': 'https://www.twothousand.com/commercial-prep-tables'},
    'Commercial Ranges': {   'name': 'Commercial Ranges',
                             'url': 'https://www.twothousand.com/commercial-ranges'},
    'Commercial Toasters': {   'name': 'Commercial Toasters',
                               'url': 'https://www.twothousand.com/commercial-toasters'},
    'Commercial Waffle Makers': {   'name': 'Commercial Waffle Makers',
                                    'url': 'https://www.twothousand.com/commercial-waffle-makers'},
    'Compartment Sinks': {   'name': 'Compartment Sinks',
                             'url': 'https://www.twothousand.com/compartment-sinks'},
    'Cookie and Cake Forming Machines': {   'name': 'Cookie and Cake Forming '
                                                    'Machines',
                                            'url': 'https://www.twothousand.com/cookie-and-cake-forming-machines'},
    'Countertop Fryers': {   'name': 'Countertop Fryers',
                             'url': 'https://www.twothousand.com/countertop-fryers'},
    'Crepe Machines': {   'name': 'Crepe Machines',
                          'url': 'https://www.twothousand.com/crepe-machines'},
    'Cup Sealers': {   'name': 'Cup Sealers',
                       'url': 'https://www.twothousand.com/cup-sealers'},
    'Donut Machines': {   'name': 'Donut Machines',
                          'url': 'https://www.twothousand.com/donut-machines'},
    'Dough Dividers Rounders': {   'name': 'Dough Dividers Rounders',
                                   'url': 'https://www.twothousand.com/dough-dividers-rounders'},
    'Dough Mixers': {   'name': 'Dough Mixers',
                        'url': 'https://www.twothousand.com/dough-mixers'},
    'Dough Press': {   'name': 'Dough Press',
                       'url': 'https://www.twothousand.com/pizza-dough-presses'},
    'Dough Rollers': {   'name': 'Dough Rollers',
                         'url': 'https://www.twothousand.com/dough-rollers'},
    'Dough Sheeters': {   'name': 'Dough Sheeters',
                          'url': 'https://www.twothousand.com/dough-sheeters'},
    'Electric Cheese Graters': {   'name': 'Electric Cheese Graters',
                                   'url': 'https://www.twothousand.com/electric-cheese-graters'},
    'Electric Food Warmers': {   'name': 'Electric Food Warmers',
                                 'url': 'https://www.twothousand.com/electric-food-warmers'},
    'Electric Smokers': {   'name': 'Electric Smokers',
                            'url': 'https://www.twothousand.com/electric-smokers'},
    'Film Wrapper, Wrap Film': {   'name': 'Film Wrapper, Wrap Film',
                                   'url': 'https://www.twothousand.com/film-wrapper-wrap-film'},
    'Fish Machines': {   'name': 'Fish Machines',
                         'url': 'https://www.twothousand.com/fish-machines'},
    'Foil Baking Cups': {   'name': 'Foil Baking Cups',
                            'url': 'https://www.twothousand.com/foil-baking-cups'},
    'Food Heat Lamps': {   'name': 'Food Heat Lamps',
                           'url': 'https://www.twothousand.com/food-heat-lamps'},
    'Fried Ice Cream Roll Machine': {   'name': 'Fried Ice Cream Roll Machine',
                                        'url': 'https://www.twothousand.com/fried-ice-cream-roll-machine'},
    'Frozen Yogurt Blending Machines': {   'name': 'Frozen Yogurt Blending '
                                                   'Machines',
                                           'url': 'https://www.twothousand.com/frozen-yogurt-blending-machines'},
    'Garlic Ginger Onion Processors': {   'name': 'Garlic Ginger Onion '
                                                  'Processors',
                                          'url': 'https://www.twothousand.com/garlic-ginger-onion-processors'},
    'Gas Hot Plates': {   'name': 'Gas Hot Plates',
                          'url': 'https://www.twothousand.com/gas-hot-plates'},
    'Hamburger and Nugget Line': {   'name': 'Hamburger and Nugget Line',
                                     'url': 'https://www.twothousand.com/hamburger-and-chicken-line'},
    'Hot Dog Grills': {   'name': 'Hot Dog Grills',
                          'url': 'https://www.twothousand.com/hot-dog-grills'},
    'Hot Dog Steamers': {   'name': 'Hot Dog Steamers',
                            'url': 'https://www.twothousand.com/hot-dog-steamers'},
    'Hot Food Display': {   'name': 'Hot Food Display',
                            'url': 'https://www.twothousand.com/hot-food-display'},
    'Ice Cream Cone Machines': {   'name': 'Ice Cream Cone Machines',
                                   'url': 'https://www.twothousand.com/ice-cream-cone-machines'},
    'Ice Cream Displays': {   'name': 'Ice Cream Displays',
                              'url': 'https://www.twothousand.com/ice-cream-displays'},
    'Ice Cream Machines': {   'name': 'Ice Cream Machines',
                              'url': 'https://www.twothousand.com/ice-cream-machines'},
    'Ice Crushers': {   'name': 'Ice Crushers',
                        'url': 'https://www.twothousand.com/ice-crushers'},
    'Immersion Blenders': {   'name': 'Immersion Blenders',
                              'url': 'https://www.twothousand.com/immersion-blenders'},
    'Jacketed Kettles': {   'name': 'Jacketed Kettles',
                            'url': 'https://www.twothousand.com/jacketed-kettles'},
    'Kebab Knives': {   'name': 'Kebab Knives',
                        'url': 'https://www.twothousand.com/kebab-knives'},
    'Manual Clipping Machines': {   'name': 'Manual Clipping Machines',
                                    'url': 'https://www.twothousand.com/manual-clipping-machines'},
    'Meat Bone Saws': {   'name': 'Meat Bone Saws',
                          'url': 'https://www.twothousand.com/meat-bone-saws'},
    'Meat Cutters': {   'name': 'Meat Cutters',
                        'url': 'https://www.twothousand.com/meat-cutters'},
    'Meat Tenderizers': {   'name': 'Meat Tenderizers',
                            'url': 'https://www.twothousand.com/meat-tenderizers'},
    'Meatball Machines': {   'name': 'Meatball Machines',
                             'url': 'https://www.twothousand.com/meatball-machines'},
    'Milk Shakers': {   'name': 'Milk Shakers',
                        'url': 'https://www.twothousand.com/milk-shakers'},
    'Noodle Machines': {   'name': 'Noodle Machines',
                           'url': 'https://www.twothousand.com/noodle-machines'},
    'Nuts Peeling Machines': {   'name': 'Nuts Peeling Machines',
                                 'url': 'https://www.twothousand.com/nuts-peeling-machines'},
    'Pasta Production Line': {   'name': 'Pasta Production Line',
                                 'url': 'https://www.twothousand.com/pasta-production-line'},
    'Peanut Butter Machines': {   'name': 'Peanut Butter Machines',
                                  'url': 'https://www.twothousand.com/peanut-butter-machines'},
    'Plate Stacking Trolleys': {   'name': 'Plate Stacking Trolleys',
                                   'url': 'https://www.twothousand.com/plate-stacking-trolleys'},
    'Popcorn Machines': {   'name': 'Popcorn Machines',
                            'url': 'https://www.twothousand.com/popcorn-machines'},
    'Potato Cutter Machines': {   'name': 'Potato Cutter Machines',
                                  'url': 'https://www.twothousand.com/potato-cutter-machines'},
    'Rapid Cook Oven': {   'name': 'Rapid Cook Oven',
                           'url': 'https://www.twothousand.com/rapid-cook-oven'},
    'Reach in Refrigerators': {   'name': 'Reach in Refrigerators',
                                  'url': 'https://www.twothousand.com/reach-in-refrigerators'},
    'Refrigerated Sushi Cases': {   'name': 'Refrigerated Sushi Cases',
                                    'url': 'https://www.twothousand.com/refrigerated-sushi-cases'},
    'Restaurant Steamers': {   'name': 'Restaurant Steamers',
                               'url': 'https://www.twothousand.com/restaurant-steamers'},
    'Salamander Grills': {   'name': 'Salamander Grills',
                             'url': 'https://www.twothousand.com/salamander-grills'},
    'Sausage Fillers': {   'name': 'Sausage Fillers',
                           'url': 'https://www.twothousand.com/sausage-fillers'},
    'Sausage Making Equipment': {   'name': 'Sausage Making Equipment',
                                    'url': 'https://www.twothousand.com/sausage-making-equipment'},
    'Sealing Machines': {   'name': 'Sealing Machines',
                            'url': 'https://www.twothousand.com/sealing-machines'},
    'Shawarma Machines': {   'name': 'Shawarma Machines',
                             'url': 'https://www.twothousand.com/shawarma-machines'},
    'Shrink Packing Machines': {   'name': 'Shrink Packing Machines',
                                   'url': 'https://www.twothousand.com/shrink-packing-machines'},
    'Slush Machines': {   'name': 'Slush Machines',
                          'url': 'https://www.twothousand.com/slush-machines'},
    'Soybean Grinders': {   'name': 'Soybean Grinders',
                            'url': 'https://www.twothousand.com/soybean-grinders'},
    'Stainless Steel Cabinets': {   'name': 'Stainless Steel Cabinets',
                                    'url': 'https://www.twothousand.com/stainless-steel-cabinets'},
    'Stainless Steel Shelving': {   'name': 'Stainless Steel Shelving',
                                    'url': 'https://www.twothousand.com/stainless-steel-shelving'},
    'Stainless Working Tables': {   'name': 'Stainless Working Tables',
                                    'url': 'https://www.twothousand.com/stainless-working-tables'},
    'Stand Mixers': {   'name': 'Stand Mixers',
                        'url': 'https://www.twothousand.com/stand-mixers'},
    'Steam Generators': {   'name': 'Steam Generators',
                            'url': 'https://www.twothousand.com/steam-generators'},
    'Steam Pans': {   'name': 'Steam Pans',
                      'url': 'https://www.twothousand.com/steam-pans'},
    'Super Market Display': {   'name': 'Super Market Display',
                                'url': 'https://www.twothousand.com/super-market-merchandisers'},
    'Tandoor Ovens': {   'name': 'Tandoor Ovens',
                         'url': 'https://www.twothousand.com/tandoor-ovens'},
    'Turnover Machines': {   'name': 'Turnover Machines',
                             'url': 'https://www.twothousand.com/turnover-machines'},
    'Undercounter Refrigerators': {   'name': 'Undercounter Refrigerators',
                                      'url': 'https://www.twothousand.com/undercounter-refrigerators'},
    'Utility Carts': {   'name': 'Utility Carts',
                         'url': 'https://www.twothousand.com/utility-carts'},
    'Vacuum Packers': {   'name': 'Vacuum Packers',
                          'url': 'https://www.twothousand.com/vacuum-packers'},
    'Vegetable Choppers': {   'name': 'Vegetable Choppers',
                              'url': 'https://www.twothousand.com/vegetable-choppers'},
    'Vegetable Spin Dryers': {   'name': 'Vegetable Spin Dryers',
                                 'url': 'https://www.twothousand.com/vegetable-spin-dryers'},
    'Vegetable and Fruit Processing ': {   'name': 'Vegetable and Fruit '
                                                   'Processing ',
                                           'url': 'https://www.twothousand.com/vegetable-and-fruit-processing'},
    'Vegetable and Meat Processors': {   'name': 'Vegetable and Meat '
                                                 'Processors',
                                         'url': 'https://www.twothousand.com/vegetable-and-meat-processors'},
    'Walk - in Cold Rooms': {   'name': 'Walk - in Cold Rooms',
                                'url': 'https://www.twothousand.com/walk-in-cold-rooms'},
    'Warewashers': {   'name': 'Warewashers',
                       'url': 'https://www.twothousand.com/warewashers'},
    'Water Boilers': {   'name': 'Water Boilers',
                         'url': 'https://www.twothousand.com/water-boilers'},
    'Wine Coolers': {   'name': 'Wine Coolers',
                        'url': 'https://www.twothousand.com/wine-coolers'},
    'Yogurt Beverage Dispensers': {   'name': 'Yogurt Beverage Dispensers',
                                      'url': 'https://www.twothousand.com/yogurt-dispensers'}}